// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[] = SECRET_SSID;           // Network SSID (name)
const char PASS[] = SECRET_OPTIONAL_PASS;  // Network password (use for WPA, or use as key for WEP)

void onRgbLightChange();

float a_x;
float a_y;
float a_z;
CloudColoredLight rgb_light;

void initProperties() {
  ArduinoCloud.addProperty(a_x, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(a_y, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(a_z, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(rgb_light, READWRITE, ON_CHANGE, onRgbLightChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
